-- Supabase schema for Forum and Support (create in Supabase SQL editor)

-- Forum posts and answers (with author tracking)
create table if not exists forum_posts (
  id bigint generated by default as identity primary key,
  question text not null,
  author_id uuid references auth.users(id) default null,
  created_at timestamptz default now()
);

create table if not exists forum_answers (
  id bigint generated by default as identity primary key,
  post_id bigint references forum_posts(id) on delete cascade,
  text text not null,
  author_id uuid references auth.users(id) default null,
  created_at timestamptz default now()
);

-- Support requests (internal)
create table if not exists support_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) default null,
  message text not null,
  created_at timestamptz default now()
);

-- Enable RLS and policies
alter table forum_posts enable row level security;
alter table forum_answers enable row level security;
alter table support_requests enable row level security;

-- If you already have these tables from an earlier run without the
-- `author_id`/`user_id` columns, add them idempotently so policies
-- below won't fail with "column does not exist".
alter table forum_posts add column if not exists author_id uuid references auth.users(id) default null;
alter table forum_answers add column if not exists author_id uuid references auth.users(id) default null;
alter table support_requests add column if not exists user_id uuid references auth.users(id) default null;

create policy "forum_posts_select" on forum_posts for select using (true);
-- Allow authenticated users to insert posts; require author_id matches auth.uid() if provided
create policy "forum_posts_insert" on forum_posts for insert with check (auth.uid() IS NOT NULL);
-- Allow owners to update/delete their posts (owner only)
create policy "forum_posts_manage_own" on forum_posts for update using (author_id = auth.uid()) with check (author_id = auth.uid());
create policy "forum_posts_delete_own" on forum_posts for delete using (author_id = auth.uid());

-- Forum answers policies
create policy "forum_answers_select" on forum_answers for select using (true);
create policy "forum_answers_insert" on forum_answers for insert with check (auth.uid() IS NOT NULL);
create policy "forum_answers_update_own" on forum_answers for update using (author_id = auth.uid()) with check (author_id = auth.uid());
create policy "forum_answers_delete_own" on forum_answers for delete using (author_id = auth.uid());

-- Support requests policies
-- Only allow select for admin roles if you have an admin role; otherwise restrict. For now, allow authenticated users to insert support requests.
create policy "support_insert_authenticated" on support_requests for insert with check (auth.uid() IS NOT NULL);
-- Admin select: adapt to your project's JWT claim for role. Example assumes jwt.claims.role = 'admin'.
create policy "support_select_admin" on support_requests for select using (current_setting('jwt.claims.role', true) = 'admin');

-- NOTE: The above 'auth.role()' and jwt.claims.role usage depends on your Supabase JWT setup.
-- You may need to adapt policies to your project's auth/claims configuration.

-- ------------------------------------------------------------------
-- Production-ready RLS policies (idempotent)
-- - Require authenticated users for inserts/updates/deletes
-- - Allow public selects for forum posts/answers, but restrict support to admins
-- - Admin detection uses jwt.claims.role = 'admin' (adapt if your claim differs)
-- ------------------------------------------------------------------

-- Forum posts: public read, authenticated create/update/delete by owner only
drop policy if exists "forum_posts_select" on forum_posts;
create policy "forum_posts_select" on forum_posts for select using (true);

drop policy if exists "forum_posts_insert" on forum_posts;
create policy "forum_posts_insert" on forum_posts
  for insert
  with check (auth.uid() IS NOT NULL AND author_id = auth.uid());

drop policy if exists "forum_posts_update_own" on forum_posts;
create policy "forum_posts_update_own" on forum_posts
  for update
  using (author_id = auth.uid())
  with check (author_id = auth.uid());

drop policy if exists "forum_posts_delete_own" on forum_posts;
create policy "forum_posts_delete_own" on forum_posts
  for delete
  using (author_id = auth.uid());

-- Forum answers: public read, authenticated create/update/delete by owner only
drop policy if exists "forum_answers_select" on forum_answers;
create policy "forum_answers_select" on forum_answers for select using (true);

drop policy if exists "forum_answers_insert" on forum_answers;
create policy "forum_answers_insert" on forum_answers
  for insert
  with check (auth.uid() IS NOT NULL AND author_id = auth.uid());

drop policy if exists "forum_answers_update_own" on forum_answers;
create policy "forum_answers_update_own" on forum_answers
  for update
  using (author_id = auth.uid())
  with check (author_id = auth.uid());

drop policy if exists "forum_answers_delete_own" on forum_answers;
create policy "forum_answers_delete_own" on forum_answers
  for delete
  using (author_id = auth.uid());

-- Support requests: allow authenticated users to insert their own requests;
-- selects/management only for admins (jwt.claims.role = 'admin')
drop policy if exists "support_insert_authenticated" on support_requests;
create policy "support_insert_authenticated" on support_requests
  for insert
  with check (auth.uid() IS NOT NULL AND user_id = auth.uid());

drop policy if exists "support_select_admin" on support_requests;
create policy "support_select_admin" on support_requests
  for select
  using (current_setting('jwt.claims.role', true) = 'admin');

drop policy if exists "support_update_admin" on support_requests;
create policy "support_update_admin" on support_requests
  for update
  using (current_setting('jwt.claims.role', true) = 'admin')
  with check (current_setting('jwt.claims.role', true) = 'admin');

drop policy if exists "support_delete_admin" on support_requests;
create policy "support_delete_admin" on support_requests
  for delete
  using (current_setting('jwt.claims.role', true) = 'admin');

-- IMPORTANT: If your client does not set `author_id`/`user_id` explicitly,
-- consider adding a DB trigger to set those columns to auth.uid() on insert.
-- Also ensure your JWT contains a `role` claim matching the admin check above.

-- Sample inserts (optional)
-- insert into forum_posts (question, author_id) values ('How do I upgrade to Premium?', 'some-uuid');
-- insert into forum_answers (post_id, text, author_id) values (1, 'Click Upgrade in Settings', 'some-uuid');

-- End of SQL
